[package]
name = "rust_task"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.16.0"
solana-program = "1.16.0"
solana-sdk = "1.16.0"
borsh = "0.10.3"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }
